name: Release Binaries

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build Linux binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build Linux binary
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/ditto-linux-amd64

      - name: Upload binary to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/ditto-linux-amd64
          fail_on_unmatched_files: false
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          update_existing: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
